export class RemunerativeWork{
public application_id:number;
public work_category_id:number
public nature_of_work:string
public start_date:Date
public end_date:Date
public mon_start_hours:number
public mon_end_hours:number
public tue_start_hours:number
public tue_end_hours:number
public wed_start_hours:number
public wed_end_hours:number
public thu_start_hours:number
public thu_end_hours:number
public fri_start_hours:number
public fri_end_hours:number
public sat_start_hours:number
public sat_end_hours:number
public sun_start_hours:number
public sun_end_hours:number
public total_working_hours:number
public remunerative_work_performed:string
public business_name:string
public reporting_person_surname:string
public reporting_person_initials:string
public contact_number:number
public reporting_person_contact_number:number
public create_time:number;
public create_user_id:number;
}